POST http://localhost:5000/event/create-staff
Content-type: application/json

{
    "name":"Дмитрий Губич",
    "salary":"20",
    "avatar":"https://res.cloudinary.com/adffergcloud/image/upload/v1638971439/gubich_zgpphi.jpg",
    "description":"1",
    "type_of_events":"wedding,birthday,graduation"
}