POST http://localhost:5000/event/create-food
Content-type: application/json

{
    "name":"Шашлык",
    "price":"10",
    "image":"https://res.cloudinary.com/adffergcloud/image/upload/v1638738452/pinchos_x5ge4t.jpg"
}